# Site settings
author: Andrew Capp
title: New Career at Age 50
header-img: img/home-bg.png
email: acapp909@gmail.com
copyright_name: Andrew Capp
description: > # this means to ignore newlines until "baseurl:"
  Transitioning from accounting to IT
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ACAPP-dev

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
